### ISSUE TITLE
Program freezes on Combat_Crit.xnb

### ISSUE THREAD

**Issue by vitorgcury** [Antag99/TExtract#4]
Program does not extract any file, freezing from the start, at Combat_Crit.xnb file.

**Comment by MaddTheSane** [comment]
Can confirm. Ran into the problem on my Mac, and Java spat out this to the terminal window I was using:

```
Exception in thread "Thread-1" ai: unsupported asset type: ReLogic.Graphics.DynamicSpriteFontReader
	at aj.a(Unknown Source)
	at L.a(Unknown Source)
	at L.a(Unknown Source)
	at L.a(Unknown Source)
	at Q.run(Unknown Source)
```

**Comment by legsofjelly** [comment]
All you need to do is go and find your Terraria\Content file, and temporarely re-place your Fonts folder to somewhere else.

**Comment by PaweX** [comment]
Error still present
